language: python
python:
- '3.6'
script:
- python setup.py test
deploy:
  provider: pypi
  user: gunmer
  password:
    secure: IWD7eLnPxEUsPc7NhMw8axO63sDcO3ES9ZrQS5VXo1E5JSxWAac78nnSOgRZh5xNsMGh8gbSGid1XrQw0j5xwR+WrmlOhtE1ili4OTFJeMfDISM67BGIuu227DTX/FVqe4k55JfrP+y6kPG3i61QyieTpLY3czdg3QrRvLkjMusuxfFIkGgQsw9CfMwBCmGRCsvOcZhtUBJLnvRCO+7cL1V5mt/qiG2VtAuBhdbQQ6yr+0YvSJADRRhx9r4/yPwgf9OgX8ZpHUcGL+2TeRRN/BUoxBiaQ31QIkqMtQ6WRFODTp+y2f9JW5nwESYIpX8foHveu/5J5e+gDNcqkYMvMAEi2Cws2912feBMlzgnJUhcqF7MXn90yV5zUoM2iNVJ1psQUwdOyV/rVvnwXuk2DScXXMj2Ur9Y1OVhwvccgcwpMJ3PF0oBB792PeI0HvGvRNIWhjEw3siAGlPn//Bzgi+AlUTS1qMTcgxZrSib3OIf813CGvY2Tr2G2S+Q5bty3Qtorqcubx69pq4Lfvdmwi8wUFOAYw2tox/300nOlWJBsuX2mlbjGk+aCG2wzTDIWAniWVf+g1gQZIfXMCI2WNT2vT+isInSySF2NQeUdPnh4Zq1n33wc7awARH0ZQ71tfNHL2gPcatK3DbNawTYBPvC6Q6T40ovirOMi81LjcM=
